2 css
ltfscode/dz-html pull request #2
Opened 2024-03-15 21:00 UTC by ltfscode

2024-03-17 17:59 UTC, GitEsense requested changes
Необходимо привести блоки в соответствие макету (отступы, размеры шрифта, положение элементов (за исключением выделенных блоков)
![image](https://github.com/ltfscode/dz-html/assets/101252030/c038ffc2-6550-4e23-80a9-4f430a00162e)
выделенные блоки будут выставляться после изучения flexbox, всё остальное необходимо привести в соответствие, например:

блок header у нас имеет размер 1080px (если посмотреть на отступы слева и справа)
body имеет размер 1440px (максимум) - об этом говорит тот же блок header
![image](https://github.com/ltfscode/dz-html/assets/101252030/24f4364b-f5bf-4dde-899b-4928b56e19e7)

картинка имеет 896px
а блок текста 708px
следовательно им можно установить размеры (посмотрите на max-width) и воспользоваться margin: 0 auto (об этом было в упражнениях, ознакомьтесь)

2024-03-17 17:59 UTC, GitEsense commented on 1-blog/index.html
>        </div>
Отсутствует иконка логотипа, её реализуем либо через css, либо img тегом

2024-03-17 17:59 UTC, GitEsense commented on 1-blog/index.html
>        </div>
Необходимо привести в соответствие (радиусы, размеры, положение) - всё согласно макету)

2024-03-19 10:06 UTC, GitEsense requested changes
В целом всё хорошо, но... блоки "artcl-1 / 2 / 3" - проверьте отступы, так же заголовок требует указания размера в соответствии с макетом (будьте более внимательны), например у инпута border другого цвета (или отсутствует), а вот над формой надо поработать, форма должна быть максимально похожа на макет (это Вы уже можете сделать сейчас, вопрос будет только в позиционировании (абсолютном по центру экрана) и сложность может возникнуть с фамилия + имя (в одну строку через 1 пиксель)

2024-03-20 08:47 UTC, GitEsense approved these changes
Всё ок, но надо поправить что осталось - в комментариях

2024-03-20 08:47 UTC, GitEsense commented on 1-blog/style.css
> +  padding: 0 367px;
Вот это страшный padding, потому что блок мы не ограничивает, а от размера layout будет меняться, чтобы сделать блок нужного размера - воспользуйтесь max-width: 708px

2024-03-20 08:47 UTC, GitEsense commented on 1-blog/style.css
> +  margin: 0 auto 30px;
Тут высота (height) будет абсолютно лишней, а ширину лучше так же указать через max-width (не более), в то время как width статичный

2024-03-20 08:47 UTC, GitEsense commented on 2-form/style.css
> +  background-color: #9e4747;
background: linear-gradient(
            225deg,
            #fdc5c5 25.45%,
            rgba(242, 152, 222, 0) 100%
        ),
        linear-gradient(225deg, #ffa5a5 33.09%, rgba(255, 255, 255, 0) 82.34%),
        #f39494;

2024-03-20 08:47 UTC, GitEsense commented on 2-form/style.css
> +  height: 16px;
Вот это убрать (заменить), т.к. у Вас на инпут идут стили, то тут можно переобъявить
width: unset
height: unset
всё остальное можно убрать, стилизация делается через label, но это уже будем потом думать, сейчас просто поставьте "как есть" и в целом всё отлично

2024-03-20 08:47 UTC, GitEsense commented on 1-blog/style.css
> +}
Тут по прежнему 
![chrome_2BrInACbKv](https://github.com/ltfscode/dz-html/assets/101252030/edffcaec-1578-4836-b161-40bdfd4906a2)

нет отступов между текстовыми блоками

2024-03-20 09:07 UTC, ltfscode commented
День добрый. Я это исправлю и могу merge-ть? И подскажите, у меня явно с
чем-то проблемы или это тупо невнимательность?

ср, 20 мар. 2024 г., 11:47 kld_ch_a ***@***.***>:

> ***@***.**** approved this pull request.
>
> Всё ок, но надо поправить что осталось - в комментариях
> ------------------------------
>
> In 1-blog/style.css
> <https://github.com/ltfscode/dz-html/pull/2#discussion_r1531668547>:
>
> > +  line-height: 38px;
> +}
> +
> +.color-images {
> +  margin: 0 0 69px 0;
> +  text-align: center;
> +}
> +
> +.clr {
> +  border-radius: 5px;
> +  width: 896px;
> +  height: 594px;
> +}
> +
> +article {
> +  padding: 0 367px;
>
> Вот это страшный padding, потому что блок мы не ограничивает, а от размера
> layout будет меняться, чтобы сделать блок нужного размера - воспользуйтесь
> max-width: 708px
> ------------------------------
>
> In 1-blog/style.css
> <https://github.com/ltfscode/dz-html/pull/2#discussion_r1531674631>:
>
> > +  width: 525px;
> +  height: 76px;
> +  margin: 0 auto 30px;
>
> Тут высота (height) будет абсолютно лишней, а ширину лучше так же указать
> через max-width (не более), в то время как width статичный
> ------------------------------
>
> In 2-form/style.css
> <https://github.com/ltfscode/dz-html/pull/2#discussion_r1531688786>:
>
> > @@ -0,0 +1,164 @@
> +* {
> +  margin: 0;
> +  padding: 0;
> +  box-sizing: border-box;
> +  font-family: 'Open Sans', sans-serif;
> +}
> +
> +body {
> +  background-color: #9e4747;
>
> background: linear-gradient(
> 225deg,
> #fdc5c5 25.45%,
> rgba(242, 152, 222, 0) 100%
> ),
> linear-gradient(225deg, #ffa5a5 33.09%, rgba(255, 255, 255, 0) 82.34%),
> #f39494;
> ------------------------------
>
> In 2-form/style.css
> <https://github.com/ltfscode/dz-html/pull/2#discussion_r1531691548>:
>
> > +  width: 15px;
> +  height: 16px;
>
> Вот это убрать (заменить), т.к. у Вас на инпут идут стили, то тут можно
> переобъявить
> width: unset
> height: unset
> всё остальное можно убрать, стилизация делается через label, но это уже
> будем потом думать, сейчас просто поставьте "как есть" и в целом всё отлично
> ------------------------------
>
> In 1-blog/style.css
> <https://github.com/ltfscode/dz-html/pull/2#discussion_r1531692597>:
>
> > +.artcl-1 {
> +  font-size: 20px;
> +  font-weight: 400;
> +  line-height: 32px;
> +}
> +
> +.artcl-2 {
> +  font-size: 16px;
> +  font-weight: 400;
> +  line-height: 30px;
> +}
> +
> +.frt-text {
> +  text-align: center;
> +  font-size: 16px;
> +  font-weight: 400;
> +  line-height: 28px;
> +  color: rgba(255, 255, 255, 0.6);
> +  margin: 0 0 77px 0;
> +}
>
> Тут по прежнему
> chrome_2BrInACbKv.png (view on web)
> <https://github.com/ltfscode/dz-html/assets/101252030/edffcaec-1578-4836-b161-40bdfd4906a2>
>
> нет отступов между текстовыми блоками
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ltfscode/dz-html/pull/2#pullrequestreview-1948218848>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BETJP2PQ4FLILV744S7VDS3YZFEKRAVCNFSM6AAAAABEYUYTCGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBYGIYTQOBUHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-20 09:11 UTC, GitEsense commented
> День добрый. Я это исправлю и могу merge-ть? И подскажите, у меня явно с чем-то проблемы или это тупо невнимательность?

Это невнимательность)
Да, поправите и можно в мердж

2024-03-20 09:30 UTC, merged